// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Install(arg1:context.Context):Promise<void>;

export function IsInstalled():Promise<boolean>;

export function Start(arg1:context.Context):Promise<void>;
