// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Install(arg1) {
  return window['go']['app']['App']['Install'](arg1);
}

export function IsInstalled() {
  return window['go']['app']['App']['IsInstalled']();
}

export function Start(arg1) {
  return window['go']['app']['App']['Start'](arg1);
}
